export const EC_INVALID_ITEM = "EC_INVALID_ITEM";
export const EC_INVALID_ITEMS = "EC_INVALID_ITEMS";
export const EC_INVALID_FACT = "EC_INVALID_FACT";
export const EC_INVALID_OPERATION = "EC_INVALID_OPERATION";
export const EC_INVALID_AMOUNT = "EC_INALID_AMOUNT";
export const EC_INVALID_AMOUNTS = "EC_INVALID_AMOUNTS";
export const EC_NOT_IMPLEMENTED_METHOD = "EC_NOT_IMPLEMENTED_METHOD";
export const EC_FILE_CREATION_FAILED = "EC_FILE_CREATION_FAILED";

export const EC_IMPOSSIBLE_TIMELINE = "EC_IMPOSSIBLE_TIMELINE";